theme: minima
# remote_theme: pages-themes/cayman@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
title: CSCI 5980/8980 - Machine Learning for Health
description: Course Website
include: [_pages]
header_pages:
  - _pages/index.md
  - _pages/syllabus.md
  - _pages/schedule.md
